package io.probestack.onboarding.model;

public enum AssignmentSourceType {
    ADMIN_ACCOUNT,
    BOOTSTRAP_CONFIG,
    PRINCIPAL_ASSIGNMENT,
    LEGACY_ACCESS_ASSIGNMENT,
    RESOURCE_OWNER,
    APPLICATION_INVITATION,
    TEAM_MEMBERSHIP,
    TEAM_APPLICATION_GRANT,
    DEVELOPER_SCOPE_GRANT,
    DEVELOPER_PROFILE
}
