package io.probestack.onboarding.model;

public enum AuditAction {
    CREATE,
    UPDATE,
    STATUS_CHANGE,
    DELETE,
    LINK_CONSUMER,
    UNLINK_CONSUMER,
    INVITE_APPLICATION_USER,
    ACCEPT_APPLICATION_INVITATION,
    REJECT_APPLICATION_INVITATION,
    REVOKE_APPLICATION_INVITATION,
    CREATE_TEAM,
    INVITE_TEAM_MEMBER,
    ACCEPT_TEAM_INVITATION,
    REJECT_TEAM_INVITATION,
    REVOKE_TEAM_INVITATION,
    GRANT_TEAM_APPLICATION,
    REVOKE_TEAM_APPLICATION
}
