package io.probestack.onboarding.model;

public enum ResourceType {
    BUSINESS_UNIT,
    PROJECT,
    APPLICATION,
    DEVELOPER,
    CONSUMER,
    ACCESS_ASSIGNMENT,
    PRINCIPAL_ROLE_ASSIGNMENT,
    APPLICATION_INVITATION,
    ACCESS_TEAM,
    TEAM_INVITATION,
    TEAM_APPLICATION_GRANT
}
